name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login
        run: docker login -u ${{secrets.DOCKER_USER}} -p "${{secrets.DOCKER_PASSWORD}}"
      - name: Build
        run: docker build --file Dockerfile --tag ${{secrets.DOCKER_USER}}/ojs-apache:latest --tag ${{secrets.DOCKER_USER}}/ojs-apache:1.0.1 .
      - name: Push
        run: docker push ${{secrets.DOCKER_USER}}/ojs-apache
